// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {memory} from '../models';
import {db} from '../models';
import {app} from '../models';
import {types} from '../models';
import {chat} from '../models';
import {agent} from '../models';

export function AddMemoryCandidate(arg1:memory.AddCandidateRequest):Promise<db.MemoryCandidate>;

export function AnswerAgentTaskQuestion(arg1:string,arg2:string):Promise<db.AgentTaskControl>;

export function ArchiveMemory(arg1:string):Promise<void>;

export function BuildTaskContext(arg1:memory.TaskContextRequest):Promise<memory.TaskContext>;

export function CancelAgentTask(arg1:string):Promise<db.AgentTaskControl>;

export function ClearChat():Promise<app.AppState>;

export function CreateConversation(arg1:string):Promise<db.Conversation>;

export function DeleteConversation(arg1:string):Promise<void>;

export function DisablePlugin(arg1:string):Promise<void>;

export function EnablePlugin(arg1:string):Promise<void>;

export function GenerateProactiveMessage(arg1:string):Promise<app.ChatReply>;

export function GetActiveProvider():Promise<types.ProviderConfig>;

export function GetAgentTask(arg1:string):Promise<db.AgentTask>;

export function GetMessages(arg1:string):Promise<Array<db.Message>>;

export function GetProviders():Promise<Record<string, types.ProviderConfig>>;

export function GetPluginConfig(arg1:string):Promise<Record<string, any>>;

export function GetState():Promise<app.AppState>;

export function GetTokenUsageByProviderModel():Promise<Array<db.TokenUsageSummary>>;

export function GetTokenUsageSummary():Promise<db.TokenUsageSummary>;

export function GetTokenUsageSummaryByConversation(arg1:string):Promise<db.TokenUsageSummary>;

export function InvokePluginAction(arg1:string,arg2:string,arg3:Record<string, any>):Promise<Record<string, any>>;

export function ListAgentTaskEvents(arg1:string):Promise<Array<db.AgentTaskEvent>>;

export function ListAgentTasks(arg1:string,arg2:number):Promise<Array<db.AgentTask>>;

export function ListConversations():Promise<Array<db.Conversation>>;

export function ListMemoryCandidates(arg1:string,arg2:number):Promise<Array<db.MemoryCandidate>>;

export function ListPlugins():Promise<app.PluginListReply>;

export function ListTokenUsageByConversation(arg1:string):Promise<Array<db.TokenUsageRecord>>;

export function ObserveScreen(arg1:string):Promise<app.ChatReply>;

export function ProbeFishLive():Promise<app.FishLiveProbeResult>;

export function PromoteMemoryCandidate(arg1:string):Promise<db.UserMemory>;

export function RejectMemoryCandidate(arg1:string):Promise<void>;

export function SearchMemories(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<db.UserMemory>>;

export function SendAgentTaskControl(arg1:string,arg2:string,arg3:Record<string, any>):Promise<db.AgentTaskControl>;

export function SendMessage(arg1:string):Promise<app.ChatReply>;

export function SetActiveProvider(arg1:string,arg2:string):Promise<void>;

export function SetPluginConfig(arg1:string,arg2:Record<string, any>):Promise<void>;

export function StartRealtimeSpeech(arg1:string):Promise<app.SpeechStreamStart>;

export function StreamChat(arg1:chat.ChatRequest):Promise<void>;

export function SubmitAgentTask(arg1:agent.TaskSpec):Promise<db.AgentTask>;

export function SynthesizeSpeech(arg1:string):Promise<app.SpeechReply>;

export function SynthesizeSpeechStream(arg1:string):Promise<app.SpeechStreamStart>;

export function TranscribeAudio(arg1:string,arg2:string,arg3:string):Promise<app.ASRReply>;

export function UpdatePetHitTest(arg1:app.PetHitTestState):Promise<void>;

export function UpdateProvider(arg1:string,arg2:types.ProviderConfig):Promise<void>;

export function UpsertConversationSummary(arg1:string,arg2:string,arg3:number):Promise<db.ConversationSummary>;

export function UpsertMemory(arg1:memory.UpsertMemoryRequest):Promise<db.UserMemory>;
