// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMemoryCandidate(arg1) {
  return window['go']['app']['App']['AddMemoryCandidate'](arg1);
}

export function AnswerAgentTaskQuestion(arg1, arg2) {
  return window['go']['app']['App']['AnswerAgentTaskQuestion'](arg1, arg2);
}

export function ArchiveMemory(arg1) {
  return window['go']['app']['App']['ArchiveMemory'](arg1);
}

export function BuildTaskContext(arg1) {
  return window['go']['app']['App']['BuildTaskContext'](arg1);
}

export function CancelAgentTask(arg1) {
  return window['go']['app']['App']['CancelAgentTask'](arg1);
}

export function ClearChat() {
  return window['go']['app']['App']['ClearChat']();
}

export function CreateConversation(arg1) {
  return window['go']['app']['App']['CreateConversation'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['app']['App']['DeleteConversation'](arg1);
}

export function DisablePlugin(arg1) {
  return window['go']['app']['App']['DisablePlugin'](arg1);
}

export function EnablePlugin(arg1) {
  return window['go']['app']['App']['EnablePlugin'](arg1);
}

export function GenerateProactiveMessage(arg1) {
  return window['go']['app']['App']['GenerateProactiveMessage'](arg1);
}

export function GetActiveProvider() {
  return window['go']['app']['App']['GetActiveProvider']();
}

export function GetAgentTask(arg1) {
  return window['go']['app']['App']['GetAgentTask'](arg1);
}

export function GetMessages(arg1) {
  return window['go']['app']['App']['GetMessages'](arg1);
}

export function GetProviders() {
  return window['go']['app']['App']['GetProviders']();
}

export function GetPluginConfig(arg1) {
  return window['go']['app']['App']['GetPluginConfig'](arg1);
}

export function GetState() {
  return window['go']['app']['App']['GetState']();
}

export function GetTokenUsageByProviderModel() {
  return window['go']['app']['App']['GetTokenUsageByProviderModel']();
}

export function GetTokenUsageSummary() {
  return window['go']['app']['App']['GetTokenUsageSummary']();
}

export function GetTokenUsageSummaryByConversation(arg1) {
  return window['go']['app']['App']['GetTokenUsageSummaryByConversation'](arg1);
}

export function InvokePluginAction(arg1, arg2, arg3) {
  return window['go']['app']['App']['InvokePluginAction'](arg1, arg2, arg3);
}

export function ListAgentTaskEvents(arg1) {
  return window['go']['app']['App']['ListAgentTaskEvents'](arg1);
}

export function ListAgentTasks(arg1, arg2) {
  return window['go']['app']['App']['ListAgentTasks'](arg1, arg2);
}

export function ListConversations() {
  return window['go']['app']['App']['ListConversations']();
}

export function ListMemoryCandidates(arg1, arg2) {
  return window['go']['app']['App']['ListMemoryCandidates'](arg1, arg2);
}

export function ListPlugins() {
  return window['go']['app']['App']['ListPlugins']();
}

export function ListTokenUsageByConversation(arg1) {
  return window['go']['app']['App']['ListTokenUsageByConversation'](arg1);
}

export function ObserveScreen(arg1) {
  return window['go']['app']['App']['ObserveScreen'](arg1);
}

export function ProbeFishLive() {
  return window['go']['app']['App']['ProbeFishLive']();
}

export function PromoteMemoryCandidate(arg1) {
  return window['go']['app']['App']['PromoteMemoryCandidate'](arg1);
}

export function RejectMemoryCandidate(arg1) {
  return window['go']['app']['App']['RejectMemoryCandidate'](arg1);
}

export function SearchMemories(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SearchMemories'](arg1, arg2, arg3, arg4);
}

export function SendAgentTaskControl(arg1, arg2, arg3) {
  return window['go']['app']['App']['SendAgentTaskControl'](arg1, arg2, arg3);
}

export function SendMessage(arg1) {
  return window['go']['app']['App']['SendMessage'](arg1);
}

export function SetPluginConfig(arg1, arg2) {
  return window['go']['app']['App']['SetPluginConfig'](arg1, arg2);
}

export function SetActiveProvider(arg1, arg2) {
  return window['go']['app']['App']['SetActiveProvider'](arg1, arg2);
}

export function StartRealtimeSpeech(arg1) {
  return window['go']['app']['App']['StartRealtimeSpeech'](arg1);
}

export function StreamChat(arg1) {
  return window['go']['app']['App']['StreamChat'](arg1);
}

export function SubmitAgentTask(arg1) {
  return window['go']['app']['App']['SubmitAgentTask'](arg1);
}

export function SynthesizeSpeech(arg1) {
  return window['go']['app']['App']['SynthesizeSpeech'](arg1);
}

export function SynthesizeSpeechStream(arg1) {
  return window['go']['app']['App']['SynthesizeSpeechStream'](arg1);
}

export function TranscribeAudio(arg1, arg2, arg3) {
  return window['go']['app']['App']['TranscribeAudio'](arg1, arg2, arg3);
}

export function UpdatePetHitTest(arg1) {
  return window['go']['app']['App']['UpdatePetHitTest'](arg1);
}

export function UpdateProvider(arg1, arg2) {
  return window['go']['app']['App']['UpdateProvider'](arg1, arg2);
}

export function UpsertConversationSummary(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpsertConversationSummary'](arg1, arg2, arg3);
}

export function UpsertMemory(arg1) {
  return window['go']['app']['App']['UpsertMemory'](arg1);
}
