// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearChat() {
  return window['go']['main']['App']['ClearChat']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SynthesizeSpeech(arg1) {
  return window['go']['main']['App']['SynthesizeSpeech'](arg1);
}
