// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearChat() {
  return window['go']['main']['App']['ClearChat']();
}

export function GenerateProactiveMessage(arg1) {
  return window['go']['main']['App']['GenerateProactiveMessage'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ListPlugins() {
  return window['go']['main']['App']['ListPlugins']();
}

export function ObserveScreen(arg1) {
  return window['go']['main']['App']['ObserveScreen'](arg1);
}

export function ProbeFishLive() {
  return window['go']['main']['App']['ProbeFishLive']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function StartRealtimeSpeech(arg1) {
  return window['go']['main']['App']['StartRealtimeSpeech'](arg1);
}

export function SynthesizeSpeech(arg1) {
  return window['go']['main']['App']['SynthesizeSpeech'](arg1);
}

export function SynthesizeSpeechStream(arg1) {
  return window['go']['main']['App']['SynthesizeSpeechStream'](arg1);
}

export function TranscribeAudio(arg1, arg2, arg3) {
  return window['go']['main']['App']['TranscribeAudio'](arg1, arg2, arg3);
}

export function UpdatePetHitTest(arg1) {
  return window['go']['main']['App']['UpdatePetHitTest'](arg1);
}

export function UpdateRuntimeSettings(arg1) {
  return window['go']['main']['App']['UpdateRuntimeSettings'](arg1);
}
