// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearChat():Promise<main.AppState>;

export function GetState():Promise<main.AppState>;

export function SendMessage(arg1:string):Promise<main.ChatReply>;

export function SynthesizeSpeech(arg1:string):Promise<main.SpeechReply>;
