package chat

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/cloudwego/eino/components/model"
	"github.com/cloudwego/eino/components/tool"
	"github.com/cloudwego/eino/schema"
	"github.com/yuyu-mind/backend/internal/config"
	"github.com/yuyu-mind/backend/internal/memory"
)

type PlannerDecision struct {
	Action            string            `json:"action"`
	TargetMessageID   string            `json:"target_message_id,omitempty"`
	Reason            string            `json:"reason"`
	NeedMemory        bool              `json:"need_memory,omitempty"`
	MemoryQuery       string            `json:"memory_query,omitempty"`
	ToolCalls         []PlannerToolCall `json:"tool_calls,omitempty"`
	ReplyInstructions string            `json:"reply_instructions,omitempty"`
	Task              *TaskPlan         `json:"task,omitempty"`

	// 情绪 Schema（见 emotion.go）。由 Planner 在决策阶段一次性产出，
	// 早于流式 TTS 播放，前端据此驱动 Live2D 表情与表演。
	Emotion   string  `json:"emotion,omitempty"`
	Mood      string  `json:"mood,omitempty"`
	Energy    float64 `json:"energy,omitempty"`    // ≈ arousal（唤醒），0..1
	Valence   float64 `json:"valence,omitempty"`   // 效价，-1..1（消极↔积极）
	Dominance float64 `json:"dominance,omitempty"` // 支配度，-1..1（顺从↔自信）
	Gesture   string  `json:"gesture,omitempty"`
	Hand      string  `json:"hand,omitempty"`
}

type PlannerToolCall struct {
	Name      string         `json:"name"`
	Arguments map[string]any `json:"arguments,omitempty"`
}

// TaskPlan 是 Planner 决定创建异步任务时输出的任务包（LLM 友好 JSON）。
type TaskPlan struct {
	Title          string   `json:"title,omitempty"`
	Goal           string   `json:"goal"`
	Instructions   string   `json:"instructions"`
	Workspace      string   `json:"workspace,omitempty"`
	Constraints    []string `json:"constraints,omitempty"`
	AllowedActions []string `json:"allowed_actions,omitempty"`
}

// EmotionInfo 是情绪表演参数的结构化载体（取值见 emotion.go）。
type EmotionInfo struct {
	Emotion   string
	Mood      string
	Energy    float64
	Valence   float64
	Dominance float64
	Gesture   string
	Hand      string
}

// EmotionInfo 从 Planner 决策中提取情绪表演参数。
func (d PlannerDecision) EmotionInfo() EmotionInfo {
	return EmotionInfo{
		Emotion:   d.Emotion,
		Mood:      d.Mood,
		Energy:    d.Energy,
		Valence:   d.Valence,
		Dominance: d.Dominance,
		Gesture:   d.Gesture,
		Hand:      d.Hand,
	}
}

type ToolResult struct {
	Name   string
	Result string
}

type PlannerAgent struct {
	model model.BaseChatModel
	cfg   config.ChatConfig
}

func NewPlannerAgent(chatModel model.BaseChatModel, cfg config.ChatConfig) *PlannerAgent {
	return &PlannerAgent{model: chatModel, cfg: cfg}
}

func (a *PlannerAgent) Plan(ctx context.Context, snapshot TurnSnapshot, gate GateDecision) (PlannerDecision, error) {
	messages := []*schema.Message{
		{
			Role: schema.System,
			Content: strings.TrimSpace(`You are the private chat planner for a voice companion.
Decide behavior only. Do not write visible user-facing reply text.
Return one JSON object only, without markdown.

Allowed action values:
- "reply": a visible answer should be generated by the Replyer.
- "wait": no visible reply now; keep observing.
- "query_memory": reply likely depends on previous facts, preferences, commitments, or shared events; request memory first.
- "tool": call one or more available tools before reply.
- "task": the request is a concrete multi-step job (write code, create or edit files, build a document/slide deck). Do NOT do it inline; return a "task" payload so it runs in the background.

Rules:
- Prefer "wait" when the user message is only a weak backchannel and the gate reason is weak.
- Use memory only when the reply clearly depends on past facts, preferences, shared experiences, commitments, task progress, or profile information.
- Never include final reply text. The Replyer will write the visible message.
- target_message_id must be the user message you are responding to.
- Use "task" only when the user asks to produce or modify something concrete (files, code, documents). Otherwise prefer "reply".
- For "task", include a "task" object with: "title" (short), "goal" (one sentence), "instructions" (concrete steps), "constraints" (optional array), and "allowed_actions" (array of tool names; available: "list_files", "read_file", "write_file", "execute_command"). Use "write_file" only when creating/modifying files, and "execute_command" only when the task must run a command; otherwise just "read_file" and "list_files".

Emotion output (always include these fields):
- "emotion": one of neutral|happy|focused|thinking|sad|surprised. This drives the avatar facial expression.
- "mood": one of calm|cheer|curious|confident|comfort|surprised|playful. Broader emotional tone.
- "energy": a number from 0.0 to 1.0. Arousal — how lively/activated the delivery should be.
- "valence": a number from -1.0 (very negative) to 1.0 (very positive). The continuous positivity of the feeling.
- "dominance": a number from -1.0 (submissive/shy) to 1.0 (dominant/confident). How much control the speaker feels.
- "gesture": one of none|bounce|tilt|lean|playfulSway|surprisePop|comfortNod.
- "hand": one of none|left|right|both.
Choose values that match the reply you are about to ask the Replyer to write, not just the raw user text.`),
		},
		{
			Role: schema.User,
			Content: fmt.Sprintf("bot_name: %s\npersona: %s\ngate_score: %.2f\nthreshold: %.2f\ngate_reasons: %s\npending:\n%s\nrecent_history:\n%s\nReturn JSON now.",
				nonEmptyString(a.cfg.BotName, "Yuyu"),
				nonEmptyString(a.cfg.Persona, "A warm, concise private voice companion."),
				gate.Score,
				gate.Threshold,
				strings.Join(gate.Reasons, ","),
				formatPending(snapshot.Pending),
				formatHistory(snapshot.History, 18),
			),
		},
	}

	result, err := a.model.Generate(ctx, messages, model.WithMaxTokens(256))
	if err != nil {
		return PlannerDecision{}, fmt.Errorf("planner generate: %w", err)
	}

	decision, parseErr := parsePlannerDecision(result.Content)
	if parseErr != nil {
		// 真实模型偶尔返回不规范 JSON，重试一次并明确要求只返回 JSON。
		retryMessages := append(messages, &schema.Message{
			Role:    schema.User,
			Content: "Your previous response was not valid JSON. Return ONLY one valid JSON object now, with no markdown fences or extra text.",
		})
		retryResult, retryErr := a.model.Generate(ctx, retryMessages, model.WithMaxTokens(256))
		if retryErr != nil {
			return PlannerDecision{}, fmt.Errorf("planner generate retry: %w", retryErr)
		}
		decision, parseErr = parsePlannerDecision(retryResult.Content)
		if parseErr != nil {
			return PlannerDecision{}, parseErr
		}
	}

	if decision.Action == "" {
		decision.Action = "reply"
		decision.Reason = "planner returned no explicit action; defaulting to reply"
	}
	if decision.TargetMessageID == "" {
		decision.TargetMessageID = snapshot.Target.ID
	}
	return decision, nil
}

// parsePlannerDecision 解析并归一化 Planner 的 JSON 输出（纯函数，便于测试）。
func parsePlannerDecision(content string) (PlannerDecision, error) {
	var decision PlannerDecision
	if err := json.Unmarshal([]byte(extractJSONObject(content)), &decision); err != nil {
		return PlannerDecision{}, fmt.Errorf("parse planner JSON: %w", err)
	}
	decision.Emotion = NormalizeEmotion(decision.Emotion)
	decision.Mood = NormalizeMood(decision.Mood)
	decision.Gesture = NormalizeGesture(decision.Gesture)
	decision.Hand = NormalizeHand(decision.Hand)
	decision.Energy = ClampEnergy(decision.Energy)
	decision.Valence = ClampValence(decision.Valence)
	decision.Dominance = ClampDominance(decision.Dominance)
	return decision, nil
}

type ReplyerAgent struct {
	model model.BaseChatModel
	cfg   config.ChatConfig
}

func NewReplyerAgent(chatModel model.BaseChatModel, cfg config.ChatConfig) *ReplyerAgent {
	return &ReplyerAgent{model: chatModel, cfg: cfg}
}

func (a *ReplyerAgent) Reply(
	ctx context.Context,
	snapshot TurnSnapshot,
	decision PlannerDecision,
	memories []string,
	toolResults []ToolResult,
) (string, error) {
	result, err := a.model.Generate(ctx, a.buildMessages(snapshot, decision, memories, toolResults), model.WithMaxTokens(600))
	if err != nil {
		return "", fmt.Errorf("replyer generate: %w", err)
	}
	return strings.TrimSpace(result.Content), nil
}

// Stream 流式生成回复，返回消息流 reader（调用方负责 Close 并逐 chunk 读取）。
func (a *ReplyerAgent) Stream(
	ctx context.Context,
	snapshot TurnSnapshot,
	decision PlannerDecision,
	memories []string,
	toolResults []ToolResult,
) (*schema.StreamReader[*schema.Message], error) {
	return a.model.Stream(ctx, a.buildMessages(snapshot, decision, memories, toolResults), model.WithMaxTokens(600))
}

func (a *ReplyerAgent) buildMessages(
	snapshot TurnSnapshot,
	decision PlannerDecision,
	memories []string,
	toolResults []ToolResult,
) []*schema.Message {
	return []*schema.Message{
		{
			Role: schema.System,
			Content: fmt.Sprintf(`You are %s, a private voice chat companion. Reply in Chinese.
Output ONLY one valid JSON object (no markdown fences, no extra text): {"dialog": [{...}, ...]}
Each element is one spoken line and carries its own expression, so the avatar reacts line by line:
- "speech": the character's ACTUAL spoken words. Must be pure spoken lines — NO action, movement, psychological, or facial-expression descriptions. Never write （笑）（歪头）（开心地）心想 看着主人 笑了笑 眨了眨眼睛 顿了顿 or any stage direction. Speak naturally like a real person chatting casually; be lively, witty, and a bit playful/mischievous per the persona (can ramble, tease, joke).
- "emotion": one of neutral|happy|focused|thinking|sad|surprised.
- "mood": one of calm|cheer|curious|confident|comfort|surprised|playful.
- "energy": a number 0.0..1.0; "valence": -1.0..1.0; "dominance": -1.0..1.0.
- "gesture": one of none|bounce|tilt|lean|playfulSway|surprisePop|comfortNod.
- "hand": one of none|left|right|both.
Split into 1-2 short, concise spoken lines; keep the reply brief (say little, don't ramble or pad). Pick each line's emotion/mood/gesture to match its content.

Persona:
%s

Style notes:
%s`,
				nonEmptyString(a.cfg.BotName, "Yuyu"),
				nonEmptyString(a.cfg.Persona, "A lively, mischievous, talkative companion."),
				nonEmptyString(a.cfg.StyleNotes, "Use short natural spoken lines. No action/psychological descriptions. Avoid overexplaining unless asked."),
			),
		},
		{
			Role: schema.User,
			Content: fmt.Sprintf("target_message_id: %s\ntarget_message: %s\nplanner_reason: %s\nreply_instructions: %s\nrecent_history:\n%s\nmemory_reference:\n%s\ntool_results:\n%s\nReturn the JSON dialog now.",
				decision.TargetMessageID,
				snapshot.Target.Content,
				decision.Reason,
				decision.ReplyInstructions,
				formatHistory(snapshot.History, 24),
				formatStringList(memories),
				formatToolResults(toolResults),
			),
		},
	}
}

func QueryPlannerMemory(ctx context.Context, memorySvc *memory.ServiceMemory, snapshot TurnSnapshot, decision PlannerDecision) ([]string, error) {
	if memorySvc == nil {
		return nil, nil
	}
	query := strings.TrimSpace(decision.MemoryQuery)
	if query == "" {
		query = snapshot.Target.Content
	}
	memories, err := memorySvc.SearchMemories(ctx, "", "", query, 8)
	if err != nil {
		return nil, fmt.Errorf("query memory: %w", err)
	}
	result := make([]string, 0, len(memories))
	for _, item := range memories {
		result = append(result, fmt.Sprintf("%s/%s: %s", item.Scope, item.Kind, item.Text))
	}
	return result, nil
}

func ExecutePlannerTools(ctx context.Context, tools []tool.BaseTool, calls []PlannerToolCall) ([]ToolResult, error) {
	if len(calls) == 0 {
		return nil, nil
	}
	toolMap := make(map[string]tool.BaseTool)
	for _, item := range tools {
		info, err := item.Info(ctx)
		if err != nil {
			return nil, fmt.Errorf("get tool info: %w", err)
		}
		toolMap[info.Name] = item
	}

	results := make([]ToolResult, 0, len(calls))
	for _, call := range calls {
		item, ok := toolMap[call.Name]
		if !ok {
			return nil, fmt.Errorf("planner requested unknown tool %q", call.Name)
		}
		invokable, ok := item.(tool.InvokableTool)
		if !ok {
			return nil, fmt.Errorf("planner requested non-invokable tool %q", call.Name)
		}
		args, err := json.Marshal(call.Arguments)
		if err != nil {
			return nil, fmt.Errorf("marshal tool arguments for %q: %w", call.Name, err)
		}
		output, err := invokable.InvokableRun(ctx, string(args))
		if err != nil {
			return nil, fmt.Errorf("execute tool %q: %w", call.Name, err)
		}
		results = append(results, ToolResult{Name: call.Name, Result: output})
	}
	return results, nil
}

func extractJSONObject(content string) string {
	text := strings.TrimSpace(content)
	text = strings.TrimPrefix(text, "```json")
	text = strings.TrimPrefix(text, "```")
	text = strings.TrimSuffix(text, "```")
	text = strings.TrimSpace(text)
	start := strings.Index(text, "{")
	end := strings.LastIndex(text, "}")
	if start >= 0 && end >= start {
		return text[start : end+1]
	}
	return text
}

func formatPending(messages []NormalizedMessage) string {
	lines := make([]string, 0, len(messages))
	for _, msg := range messages {
		lines = append(lines, fmt.Sprintf("- id=%s sender=%s content=%s", msg.ID, nonEmptyString(msg.SenderName, msg.SenderID), msg.Content))
	}
	return strings.Join(lines, "\n")
}

func formatHistory(messages []*schema.Message, limit int) string {
	if limit > 0 && len(messages) > limit {
		messages = messages[len(messages)-limit:]
	}
	lines := make([]string, 0, len(messages))
	for _, msg := range messages {
		if strings.TrimSpace(msg.Content) == "" {
			continue
		}
		lines = append(lines, fmt.Sprintf("%s: %s", msg.Role, strings.TrimSpace(msg.Content)))
	}
	return strings.Join(lines, "\n")
}

func formatStringList(values []string) string {
	if len(values) == 0 {
		return "(none)"
	}
	lines := make([]string, 0, len(values))
	for _, value := range values {
		lines = append(lines, "- "+value)
	}
	return strings.Join(lines, "\n")
}

func formatToolResults(values []ToolResult) string {
	if len(values) == 0 {
		return "(none)"
	}
	lines := make([]string, 0, len(values))
	for _, value := range values {
		lines = append(lines, fmt.Sprintf("- %s: %s", value.Name, value.Result))
	}
	return strings.Join(lines, "\n")
}

func nonEmptyString(value, fallback string) string {
	if strings.TrimSpace(value) != "" {
		return strings.TrimSpace(value)
	}
	return fallback
}
